Const VIRTUAL_WINDOW_WIDTH:Int = 1280
Const VIRTUAL_WINDOW_HEIGHT:Int = 832

Const TILE_WIDTH:Int = 28
Const TILE_HEIGHT:Int = TILE_WIDTH
Const PLAYER_WIDTH:Float = 28.0
Const PLAYER_HEIGHT:Float = 28.0

